enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching 

[Instagram]
# apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
dpi = "480"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check' 'Disable Pairip license check'"
exclusive-patches = true

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
dpi = "480"
version = "auto"
included-patches = "'Hide view count'"
